/* For selecting keyword */
SELECT `k`.`keyword`,
       `k`.`date`,
       `k`.`ad_views`,
       `k`.`ad_clicks`,
       `k`.`price`,
       `k`.`conversion_no`,
       `cu`.`name`,
       `g`.`name` AS `group_name`,
       `c`.`name` AS `campaign_name`
FROM   `ad_keyword` AS `k`
       LEFT JOIN `ad_group` AS `g`
              ON `k`.`ad_group_id` = `g`.`id`
       LEFT JOIN `ad_campaign` AS `c`
              ON `g`.`ad_campaign_id` = `c`.`id`
       LEFT JOIN `currency` AS `cu`
              ON `k`.`currency_id` = `cu`.`id`;

/* For selecting all groups and keyword under same campaign */
SELECT `c`.`name` AS `campaign_name`,
       `g`.`name` AS `group_name`,
       `k`.*
FROM   `ad_campaign` AS `c`
       LEFT JOIN `ad_group` AS `g`
              ON `c`.`id` = `g`.`ad_campaign_id`
       LEFT JOIN `ad_keyword` AS `k`
              ON `g`.`id` = `k`.`ad_group_id`
WHERE  `c`.`id` = 1;

/* Select all keyword newer than selected date. The date will be generated by PHP*/
SELECT `k`.`keyword`,
       `k`.`date`,
       `k`.`ad_views`,
       `k`.`ad_clicks`,
       `k`.`price`,
       `k`.`conversion_no`,
       `cu`.`name`,
       `g`.`name` AS `group_name`,
       `c`.`name` AS `campaign_name`
FROM   `ad_keyword` AS `k`
       LEFT JOIN `ad_group` AS `g`
              ON `k`.`ad_group_id` = `g`.`id`
       LEFT JOIN `ad_campaign` AS `c`
              ON `g`.`ad_campaign_id` = `c`.`id`
       LEFT JOIN `currency` AS `cu`
              ON `k`.`currency_id` = `cu`.`id`
WHERE  `k`.`date` > '2019-08-09 14:24:50';

/* Select all keywords ordered by view / conversion ratio*/
SELECT `k`.`keyword`,
       `k`.`date`,
       `k`.`ad_views`,
       `k`.`ad_clicks`,
       `k`.`price`,
       `k`.`conversion_no`,
       `cu`.`name`,
       `g`.`name`                               AS `group_name`,
       `c`.`name`                               AS `campaign_name`,
       ( `k`.`conversion_no` / `k`.`ad_views` ) AS `ratio`
FROM   `ad_keyword` AS `k`
       LEFT JOIN `ad_group` AS `g`
              ON `k`.`ad_group_id` = `g`.`id`
       LEFT JOIN `ad_campaign` AS `c`
              ON `g`.`ad_campaign_id` = `c`.`id`
       LEFT JOIN `currency` AS `cu`
              ON `k`.`currency_id` = `cu`.`id`
ORDER  BY `ratio` DESC;

/* Select all keywords ordered by their profitability */
SELECT `k`.`keyword`,
       `k`.`date`,
       `k`.`ad_views`,
       `k`.`ad_clicks`,
       `k`.`price`,
       `k`.`conversion_no`,
       `cu`.`name`,
       `g`.`name`                            AS `group_name`,
       `c`.`name`                            AS `campaign_name`,
       ( `k`.`conversion_no` * `k`.`price` ) AS `earings`
FROM   `ad_keyword` AS `k`
       LEFT JOIN `ad_group` AS `g`
              ON `k`.`ad_group_id` = `g`.`id`
       LEFT JOIN `ad_campaign` AS `c`
              ON `g`.`ad_campaign_id` = `c`.`id`
       LEFT JOIN `currency` AS `cu`
              ON `k`.`currency_id` = `cu`.`id`
ORDER  BY `earings` DESC;

/* Select all campaigns ordered by their profitability */
SELECT `c`.`name`                             AS `campaign_name`,
       Sum(`k`.`price` * `k`.`conversion_no`) AS `earings`
FROM   `ad_campaign` AS `c`
       LEFT JOIN `ad_group` AS `g`
              ON `c`.`id` = `g`.`ad_campaign_id`
       LEFT JOIN `ad_keyword` AS `k`
              ON `g`.`id` = `k`.`ad_group_id`
GROUP  BY `c`.`id`
ORDER  BY `earings` DESC;

/* Select campaign with the most keywords */
SELECT `c`.`name`           AS `campaign_name`,
       Count(`k`.`keyword`) AS `keywords_no`
FROM   `ad_campaign` AS `c`
       LEFT JOIN `ad_group` AS `g`
              ON `c`.`id` = `g`.`ad_campaign_id`
       LEFT JOIN `ad_keyword` AS `k`
              ON `g`.`id` = `k`.`ad_group_id`
GROUP  BY `c`.`id`
ORDER  BY `keywords_no` DESC;

/* Select top 3 profitable groups */
SELECT `c`.`name`                             AS `campaign_name`,
       `g`.`name`                             AS `group_name`,
       Sum(`k`.`price` * `k`.`conversion_no`) AS `earings`
FROM   `ad_group` AS `g`
       LEFT JOIN `ad_campaign` AS `c`
              ON `c`.`id` = `g`.`ad_campaign_id`
       LEFT JOIN `ad_keyword` AS `k`
              ON `g`.`id` = `k`.`ad_group_id`
GROUP  BY `g`.`id`
ORDER  BY `earings` DESC
LIMIT  3;

/* Select the most profitable keyword in each group */
SELECT `t`.`max_earning`,
       `k`.`keyword`,
       `g`.`name` AS `group_name`,
       `c`.`name` AS `campign_name`
FROM   (SELECT Max(`k`.`price` * `k`.`conversion_no`) AS `max_earning`,
               `k`.`ad_group_id`
        FROM   `ad_keyword` AS `k`
               LEFT JOIN `ad_group` AS `g`
                      ON `k`.`ad_group_id` = `g`.`id`
               LEFT JOIN `ad_campaign` AS `c`
                      ON `g`.`ad_campaign_id` = `c`.`id`
        GROUP  BY `k`.`ad_group_id`) AS `t`
       INNER JOIN `ad_keyword` AS `k`
               ON `k`.`ad_group_id` = `t`.`ad_group_id`
                  AND ( `k`.`price` * `k`.`conversion_no` ) = `t`.`max_earning`
       LEFT JOIN `ad_group` AS `g`
              ON `g`.`id` = `t`.`ad_group_id`
       LEFT JOIN `ad_campaign` AS `c`
              ON `c`.`id` = `g`.`ad_campaign_id`;